/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodeNodeIdRouteImport } from './routes/node.$nodeId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeNodeIdRoute = NodeNodeIdRouteImport.update({
  id: '/node/$nodeId',
  path: '/node/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sandbox': typeof SandboxRoute
  '/stats': typeof StatsRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sandbox': typeof SandboxRoute
  '/stats': typeof StatsRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sandbox': typeof SandboxRoute
  '/stats': typeof StatsRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/glossary' | '/sandbox' | '/stats' | '/node/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/glossary' | '/sandbox' | '/stats' | '/node/$nodeId'
  id: '__root__' | '/' | '/glossary' | '/sandbox' | '/stats' | '/node/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossaryRoute: typeof GlossaryRoute
  SandboxRoute: typeof SandboxRoute
  StatsRoute: typeof StatsRoute
  NodeNodeIdRoute: typeof NodeNodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$nodeId': {
      id: '/node/$nodeId'
      path: '/node/$nodeId'
      fullPath: '/node/$nodeId'
      preLoaderRoute: typeof NodeNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossaryRoute: GlossaryRoute,
  SandboxRoute: SandboxRoute,
  StatsRoute: StatsRoute,
  NodeNodeIdRoute: NodeNodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
